### ISSUE TITLE
update to cuda 12.2, cudnn 8.9, tensorflow 2.15.0

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/container-jupyter-nvidia#18]

**Comment by e-carlin** [comment]
This is turning into quite a challenge to find versions that work across all packages and hardware.

The nvidia repos only have cuda 12.0 (no 12.2) for f36 https://developer.download.nvidia.com/compute/cuda/repos/fedora36/x86_64/. Looking at v11 they don't have 11.8 but they do have 11.7. Tensorflow doesn't list cuda 11.7 as a supported version https://www.tensorflow.org/install/source#gpu. 

So we could install cuda toolkit 11.7 and hope tensorflow works (expects cuda 11.8). Or we could install cuda 12.0 and hope tensorflow works (expects cuda 12.2). 

From a bit of reading there should be compatibility within cuda major versions. But, "should" isn't a guarantee and plenty of people have reported problems. 

I don't know that there is a way to know without just trying. Since it has proved challenging to find time to update this software I'm inclined to go with the latest cuda (12) and see if things work.

**Comment by robnagler** [comment]
I avoid .0 releases as a general rule. Did you look for a fedora 37? https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#id12

**Comment by e-carlin** [comment]
I share that concern...

37 has 12.2 https://developer.download.nvidia.com/compute/cuda/repos/fedora37/x86_64/ . Will the 37 repo work?

**Comment by e-carlin** [comment]
Note for myself: Need to install torch (and related torch pacakges) too https://github.com/radiasoft/container-beamsim-jupyter/issues/92 . It should pick up on the presence of nvidia and install the gpu versions.

**Comment by robnagler** [comment]
> It should pick up on the presence of nvidia and install the gpu versions.

Does the gpu have to be present to build beamsim-gpu-jupyter?

**Comment by e-carlin** [comment]
I just asked myself the same question a few minutes ago. I see the image on our build server (no gpu) which would imply we built it there. So based on that I don't think so. Maybe it just picks up on the presence of cuda-toolkit? Not sure...

**Comment by robnagler** [comment]
I think we have to have an option to build beamsim-jupyter with a flag for gpu or cpu support. This is similar to the cascaded builds we do for python-ci (I think that's it).

**Comment by e-carlin** [comment]
Should we get rid of container-jupyter-nvidia in that case?

**Comment by robnagler** [comment]
No, we need it still at least to cascade state. Here's an example: https://github.com/radiasoft/container-sirepo-ci/blob/main/container-conf/build.sh

**Comment by e-carlin** [comment]
Sounds good. 

This prompted me to look more into what needs to be done differently for cpu vs gpu. For example, according to this our install of tensorflow is currently only for cpu https://www.tensorflow.org/install/pip#cpu. Looks like keras might be the same https://github.com/keras-team/keras

TODO: Collect all packages we use that might have a gpu implementation and figure out how to install them in cpu vs gpu way.

**Comment by robnagler** [comment]
Note that we have tf installed in rscode-ml. We might need to uninstall that rpm inside the nvidia build.
