### ISSUE TITLE
Fix tensorflow, cuda, py2 issues

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-jupyter-nvidia#2]

**Comment by robnagler** [comment]
@cfederer please fill in the errors you are having with cuda/tensorflow.

I know that I only installed tensorflow-gpu in the py3 pyenv in the docker image. The tensorflow in py2 is not gpu-enabled.

**Comment by cfederer** [comment]
![Screen Shot 2019-12-17 at 4 01 23 PM](https://user-images.githubusercontent.com/8430440/71041527-8a1dd800-20e6-11ea-9184-47b49f373a0b.png)
Attached is the error message I get only when using py3 and not py2 -- this occurs when I try and train a model, not upon importing or creating a network.

**Comment by robnagler** [comment]
Note that when using py2, it's not using the GPU. 

Can you set  
```py
tensorflow.debugging.set_log_device_placement(True)
```

This should output which device it is trying to use.

**Comment by cfederer** [comment]
Yep I realize that now and am very sad....

py2 outputs CPU

py3 outputs GPU:0

**Comment by robnagler** [comment]
I added this to your notebook [per recommendations to limit memory growth](https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-565318304):

```py
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
assert len(gpus) == 1
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
```

It does find the GPU and Keras is using TF. Then when I get to this line in the training cell:

```py
inputs = Input(x_train.shape[1:])
conv1 = Conv2D(4, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(inputs)
```

The log says it ran out of memory:

```txt
unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 15843721216
```

Then I tried [per many recommendations](https://github.com/tensorflow/tensorflow/issues/30039):

```py
config = ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.001
session = InteractiveSession(config=config)
```

But this still an out of memory error at the point of this call. 

Finally tried this [from the TF guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth):

```py
tf.config.experimental.set_virtual_device_configuration(
    gpus[0],
    [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)],
)
```

This doesn't do a thing. It should create a logical device, but this crashes the kernel:

```py
tf.config.experimental.list_logical_devices('GPU')
```

I'm kind of out of ideas.

**Comment by cfederer** [comment]
Can we shut the server down so it doesn't rack up any more $$? My latest
model has finished running and I have stored results.

**Comment by robnagler** [comment]
The instance is shut down.

**Comment by robnagler** [comment]
@cfederer I think I got it to work. It is quite noisy and tells me that is using the GPU, e.g.

```txt
2020-01-22 21:16:52.639332: I tensorflow/core/common_runtime/placer.cc:54] loss/conv2d_22_loss/mean_squared_error/Mean/reduction_indices: (Const): /job:localhost/replica:0/task:0/device:GPU:0
```

Running the notebook as a python script (and setting epochs=1), it ends successfully with:

```txt
6036/6036 [==============================] - 30s 5ms/step - loss: 5.6613 - mae: 1.3119 - val_loss: 7.0314 - val_mae: 1.5204
0.5213104128837586 minutes
```

This is not yet running on Jupyter. I just wanted to see if I could get the right versions.

BTW, do you need TensorRT?

Notes for myself:

```
dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/fedora29/x86_64/cuda-fedora29.repo
dnf install cuda-drivers
dnf install cuda-toolkit-10-1
curl -O http://developer.download.nvidia.com/compute/redist/cudnn/v7.6.5/cudnn-10.1-linux-x64-v7.6.5.32.tgz
tar --no-same-owner -xzf cudnn-10.1-linux-x64-v7.6.5.32.tgz -C /usr/local --wildcards 'cuda/lib64/libcudnn.so.*'
echo /usr/local/cuda/extras/CUPTI/lib64 >> /etc/ld.so.conf.d/cuda-10-1.conf
ldconfig
```

I'll proceed to build the Jupyter image and test with that.

**Comment by robnagler** [comment]
It seems that TensorRT is not supported for 10.1, but is for 10.0 and 10.2. However, Tensorflow seems to only be supported for 10.1. Tensorflow works without TensorRT. I suspect that our work is more training-oriented so it probably doesn't matter as much as people who are putting their networks into production.

**Comment by robnagler** [comment]
@cfederer I reinstalled the server, and it seems to be working. I copied my version of the FCNN*.ipynb notebook to your folder so you can see what it looks like when I ran it. This includes the python data set files.

Please let me know if it is working asap as I have another instance setup for debugging. Once you  are happy, I can shut down the one instance. 

We can then consider bringing up another instance in the cluster for @j-edelen at the same time.

**Comment by cfederer** [comment]
Notebook works for me as well - thanks Rob!

**Comment by robnagler** [comment]
I terminated the debug instance. We are running one GPU instance.

**Comment by j-edelen** [comment]
Thanks for taking care of this, Rob!
