### ISSUE TITLE
Upgrade to cuda-11-1

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-jupyter-nvidia#3]
cuda repos for fedora 32 do not support 10-1 https://github.com/radiasoft/download/issues/131

**Comment by robnagler** [comment]
It looks like the kernel is running 11.1 drivers (see https://github.com/radiasoft/ops/issues/567).

**Comment by e-carlin** [comment]
Good to know. That makes life easier. Please give me access to the server and I'll start working on the docker image.
