### ISSUE TITLE
middl: install gpu-elegant

### ISSUE THREAD

**Issue by cchall** [radiasoft/container-jupyter-nvidia#7]
Having access to gpu-elegant could be useful for middl

**Comment by robnagler** [comment]
@e-carlin since you are becoming our gpu expert, let me know if you want to take this on.

**Comment by e-carlin** [comment]
Ya I'd like to. I'll start looking into it later this afternoon.

**Comment by e-carlin** [comment]
@cchall do you have an example elegant file I can use to test that the executable I'm building does in fact work on the GPU?

**Comment by cchall** [comment]
Looks like the attached should work with gpu-elegant per https://www3.aps.anl.gov/forums/elegant/viewtopic.php?f=18&t=1118&p=4581&hilit=gpu+example#p4598

[beamSizeMatch1.zip](https://github.com/radiasoft/container-jupyter-nvidia/files/7729417/beamSizeMatch1.zip)

**Comment by e-carlin** [comment]
That seemed to work @cchall. Once PR #8 is merged and a new docker image is built and deployed you should be able to run the command gpu-elegant.
