### ISSUE TITLE
Hypre on V100

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/container-jupyter-nvidia#9]
Interested in testing hypre on our V100, related to https://github.com/hypre-space/hypre/issues/551

The hypre build script for Perlmutter is:

> #!/bin/bash
set -e
>
>_VERSION=2.23.0
_PACKAGE='hypre'
_MAKE_JOBS=10
>
>#This is using the default Perlmutter module set as of 11/21
module load cudatoolkit
>
>git clone https://github.com/hypre-space/hypre.git
cd hypre
git checkout tags/v${_VERSION}
cd ..
>
>_INSTALL="${HOME}/Perlmutter/hypre/${NERSC_HOST}/${_VERSION}"
echo "export HYPREHOME=${_INSTALL}" >> module.sh
>
>cd ${_PACKAGE}/src
>
>export FC=ftn
export CC=cc
export CXX=CC
export HYPRE_CUDA_SM=80
>
>_COMPFLAGS="-O3"
>
>export FFLAGS="${_COMPFLAGS}"
export F77FLAGS="${_COMPFLAGS}"
export LDFLAGS="${_OPENMP}"
export CXXFLAGS="${_COMPFLAGS}"
export CFLAGS="${_COMPFLAGS}"
_PREFIX="${_INSTALL}"
./configure \
    --prefix="${_PREFIX}" \
    --with-MPI \
    --with-cuda \
    --enable-unified-memory 
make -j${_MAKE_JOBS} test 
make install
cp config.log ${_INSTALL}

where the compiler commands are aliased to nfortran, nvcc, nvc++ based on the set of imported modules.

**Comment by robnagler** [comment]
See https://github.com/hypre-space/hypre/issues/551

Can you supply the example? If sensitive, use ops.

**Comment by sjcrs** [comment]
for the first step, just running the executable in `src/test/struct`

```
mpirun -np 1  ./struct
mpirun -np 1  ./struct -solver 1
```

The larger problem arises when hypre is called from within FLASH, and for that I'd have to supply the example in ops

**Comment by robnagler** [comment]
@e-carlin I realized this is similar to the elegant gpu approach. I think we should change the elegant gpu to use a standard environment variable, and then we can rebuild a collection of packages in a loop build.sh (this repo). Thoughts?

**Comment by e-carlin** [comment]
I don't exactly remember all of the specifics of cascading environment through the build scripts but assuming that works then I think this approach would work well.

**Comment by robnagler** [comment]
We haven't forgotten about this. Just behind on other tasks. If you give us a hard deadline, we're more likely to meet it.

**Comment by e-carlin** [comment]
@sjcrs I built an image and tested on our v100 ([struct-solver-1.txt](https://github.com/radiasoft/container-jupyter-nvidia/files/8228024/struct-solver-1.txt) and [struct.txt](https://github.com/radiasoft/container-jupyter-nvidia/files/8228025/struct.txt)).

I'm going to test a little more and then we can do a release (maybe in conjunction with our Sunday release) with hypre compiled for gpu use on gpu-jupyter. lmk if i can do anything else in the meantime.
